### ISSUE TITLE
Creating instance with two networks fails

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/deploy#3]
```
sf-client instance create --namespace testspace "myinstance33" 1 1 -d 8@cirros -n 4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f -n accc77d8-f28d-4f3e-9673-1ea270b9c624
```
The error is ```libvirt.libvirtError: XML error: Attempted double use of PCI Address 0000:00:03.0```

For reference attached is the relevant log.
```
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 API request: POST http://localhost:13000/instances
    Headers:
        ('Host', 'localhost:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODUsIm5iZiI6MTU5MzQzMDE4NSwianRpIjoiYTY2MDhlM2ItYTMyMy00MDA4LTgyOTMtNzA5YmNiOTRlNGNiIiwiZXhwIjoxNTkzNDMxMDg1LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.Qza4zQkPdN59cc1vH2QLbwyjz2vBawkJUMv1fXSDEPo')
        ('Content-Type', 'application/json')
        ('Content-Length', '421')
    Args: ()
    KWargs: {'name': 'myinstance33', 'cpus': 1, 'memory': 1, 'network': [{'network_uuid': '4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f', 'address': None, 'macaddress': None, 'model': 'virtio'}, {'network_uuid': 'accc77d8-f28d-4f3e-9673-1ea270b9c624', 'address': None, 'macaddress': None, 'model': 'virtio'}], 'disk': [{'size': 8, 'base': 'cirros', 'bus': None, 'type': 'disk'}], 'ssh_key': None, 'user_data': None, 'namespace': 'testspace'}
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-1', 'sf-2', 'sf-3'] start as candidates
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-1', 'sf-2', 'sf-3'] have enough actual CPU
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-1', 'sf-2', 'sf-3'] have enough idle CPU
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-1', 'sf-2', 'sf-3'] have enough idle RAM
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-1', 'sf-2', 'sf-3'] have enough idle disk
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have most matching networks
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have most matching images
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 instance(43015e80-1d17-4683-965f-a634b899e69b): Finish schedule, duration 0.16 seconds
Jun 29 11:29:45 andy-200628-amai3ieg-sf-1 Fetching testspace auth token from http://sf-3:13000/auth
Jun 29 11:29:45 andy-200628-amai3ieg-sf-3 API request: POST http://sf-3:13000/auth
    Headers:
        ('Host', 'sf-3:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '87')
    Args: ()
    KWargs: {'namespace': 'testspace', 'key': 'fyhhzcrbvzqbgtgfjbmjzmmhcczkclifwirgckrjykfkrswtkq'}
Jun 29 11:29:45 andy-200628-amai3ieg-sf-3 API request: POST http://sf-3:13000/instances
    Headers:
        ('Host', 'sf-3:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODUsIm5iZiI6MTU5MzQzMDE4NSwianRpIjoiZjY0MTA0ZjEtZmJlYy00ZTA2LWJiYjctNjg3MWQ4OGMyNjU5IiwiZXhwIjoxNTkzNDMxMDg1LCJpZGVudGl0eSI6InRlc3RzcGFjZSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.Z4nVjTb-bJPu8U2OGdEK2xf8elC6d3M6iqZkiQYOCxY')
        ('Content-Length', '499')
    Args: ()
    KWargs: {'name': 'myinstance33', 'cpus': 1, 'memory': 1, 'network': [{'network_uuid': '4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f', 'address': None, 'macaddress': None, 'model': 'virtio'}, {'network_uuid': 'accc77d8-f28d-4f3e-9673-1ea270b9c624', 'address': None, 'macaddress': None, 'model': 'virtio'}], 'disk': [{'size': 8, 'base': 'cirros', 'bus': None, 'type': 'disk'}], 'ssh_key': None, 'user_data': None, 'namespace': 'testspace', 'placed_on': 'sf-3', 'instance_uuid': '43015e80-1d17-4683-965f-a634b899e69b'}
Jun 29 11:29:45 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] forced as candidates
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] start as candidates
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have enough actual CPU
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have enough idle CPU
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have enough idle RAM
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have enough idle disk
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have most matching networks
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Scheduling instance(43015e80-1d17-4683-965f-a634b899e69b), ['sf-3'] have most matching images
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish schedule, duration 0.17 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Fetching system auth token from http://10.128.0.33:13000/auth
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 API request: POST http://10.128.0.33:13000/auth
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'vgeocjrqleanjhwmldfjdrrgumaitbxfhvziliqhdwewbigmsh'}
Jun 29 11:29:46 localhost gunicorn.sf.access: [9237] 10.128.0.44 - - [29/Jun/2020:11:29:46 +0000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 API request: PUT http://10.128.0.33:13000/deploy_network_node
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODYsIm5iZiI6MTU5MzQzMDE4NiwianRpIjoiMzk2YzI4OGMtMWIzNC00YzQ5LTkzZGYtNTE5NTdiMzM2ODQxIiwiZXhwIjoxNTkzNDMxMDg2LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.jkK2pFTGEq1dVnVEmQci2K2VSF1pmdKEGyR69F7HyNM')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': '4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f'}
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish enable nat, duration 0.04 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish discover mesh, duration 0.02 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish ensure mesh, duration 0.06 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 dnsmasq-dhcp[7405]: read /srv/shakenfist/dhcp/4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f/hosts
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish update dhcp, duration 0.08 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish discover mesh, duration 0.02 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish ensure mesh, duration 0.09 seconds
Jun 29 11:29:46 localhost gunicorn.sf.access: [9237] 10.128.0.44 - - [29/Jun/2020:11:29:46 +0000] "PUT /deploy_network_node HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 API request: POST http://10.128.0.33:13000/auth
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'vgeocjrqleanjhwmldfjdrrgumaitbxfhvziliqhdwewbigmsh'}
Jun 29 11:29:46 localhost gunicorn.sf.access: [9239] 10.128.0.44 - - [29/Jun/2020:11:29:46 +0000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 API request: PUT http://10.128.0.33:13000/deploy_network_node
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODYsIm5iZiI6MTU5MzQzMDE4NiwianRpIjoiNDA5MWI4MWMtMjIwYi00M2QxLWIyNGUtOTEwOWUwZWZjZDM0IiwiZXhwIjoxNTkzNDMxMDg2LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.Tu4xpOK7uKHSXApK4yOkal7Rbu2xLiCVdPQNXL2KIDA')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': 'accc77d8-f28d-4f3e-9673-1ea270b9c624'}
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish enable nat, duration 0.03 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish discover mesh, duration 0.02 seconds
Jun 29 11:29:46 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish ensure mesh, duration 0.06 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 dnsmasq-dhcp[7421]: read /srv/shakenfist/dhcp/accc77d8-f28d-4f3e-9673-1ea270b9c624/hosts
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish update dhcp, duration 0.07 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish discover mesh, duration 0.01 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish ensure mesh, duration 0.06 seconds
Jun 29 11:29:47 localhost gunicorn.sf.access: [9231] 10.128.0.44 - - [29/Jun/2020:11:29:47 +0000] "PUT /deploy_network_node HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:46 andy-200628-amai3ieg-sf-3 Fetching system auth token from http://10.128.0.33:13000/auth
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 network(4ee5ebb0-de7c-4cc2-86ff- vxid 4): Finish discover mesh, duration 0.01 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 network(4ee5ebb0-de7c-4cc2-86ff- vxid 4): Finish ensure mesh, duration 0.06 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 Fetching system auth token from http://10.128.0.33:13000/auth
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 API request: POST http://10.128.0.33:13000/auth
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'vgeocjrqleanjhwmldfjdrrgumaitbxfhvziliqhdwewbigmsh'}
Jun 29 11:29:47 localhost gunicorn.sf.access: [9237] 10.128.0.44 - - [29/Jun/2020:11:29:47 +0000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 API request: PUT http://10.128.0.33:13000/update_dhcp
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODcsIm5iZiI6MTU5MzQzMDE4NywianRpIjoiYTk3ZDdhMWYtNWNhNi00OTFkLWI1MTktOTdmZTRmY2YzZTQ0IiwiZXhwIjoxNTkzNDMxMDg3LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.QvJ1nK0ZHtboi8J7UPk03NH_BgNEMki9qYM0q5uV2jc')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': '4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f'}
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish discover mesh, duration 0.01 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish ensure mesh, duration 0.09 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 dnsmasq-dhcp[7405]: read /srv/shakenfist/dhcp/4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f/hosts
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(4ee5ebb0-de7c-4cc2-86ff-be0918ff1f1f, vxid 4): Finish update dhcp, duration 0.09 seconds
Jun 29 11:29:47 localhost gunicorn.sf.access: [9231] 10.128.0.44 - - [29/Jun/2020:11:29:47 +0000] "PUT /update_dhcp HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 network(accc77d8-f28d-4f3e-9673- vxid 3): Finish discover mesh, duration 0.01 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 network(accc77d8-f28d-4f3e-9673- vxid 3): Finish ensure mesh, duration 0.06 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 Fetching system auth token from http://10.128.0.33:13000/auth
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 API request: POST http://10.128.0.33:13000/auth
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'vgeocjrqleanjhwmldfjdrrgumaitbxfhvziliqhdwewbigmsh'}
Jun 29 11:29:47 localhost gunicorn.sf.access: [9239] 10.128.0.44 - - [29/Jun/2020:11:29:47 +0000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 API request: PUT http://10.128.0.33:13000/update_dhcp
    Headers:
        ('Host', '10.128.0.33:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTM0MzAxODcsIm5iZiI6MTU5MzQzMDE4NywianRpIjoiYTdhNTQzNjUtMGY3OC00NGZmLTk5MjctOWYzOWRiM2ExZDE4IiwiZXhwIjoxNTkzNDMxMDg3LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.hPEFNh0t0NyYuhR-7T0BLalIeGCTmHPKMwLJzQlXwh8')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': 'accc77d8-f28d-4f3e-9673-1ea270b9c624'}
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish discover mesh, duration 0.02 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish ensure mesh, duration 0.08 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 dnsmasq-dhcp[7421]: read /srv/shakenfist/dhcp/accc77d8-f28d-4f3e-9673-1ea270b9c624/hosts
Jun 29 11:29:47 andy-200628-amai3ieg-sf-1 network(accc77d8-f28d-4f3e-9673-1ea270b9c624, vxid 3): Finish update dhcp, duration 0.08 seconds
Jun 29 11:29:47 localhost gunicorn.sf.access: [9239] 10.128.0.44 - - [29/Jun/2020:11:29:47 +0000] "PUT /update_dhcp HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish ensure networks exist, duration 0.64 seconds
Jun 29 11:29:47 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish make config drive, duration 0.07 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 Found cirros versions: ['0.3.0', '0.3.1', '0.3.2', '0.3.3', '0.3.4', '0.3.5', '0.3.6', '0.4.0', '0.5.0', '0.5.1']
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish fetch image, duration 0.57 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish transcode image, duration 0.01 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish resize image, duration 0.01 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish create copy on write layer, duration 0.03 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish create domain XML, duration 0.07 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Failed to lookup domain
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 libvirtd[802]: 2020-06-29 11:29:48.681+0000: 822: error : virDomainPCIAddressReserveAddrInternal:590 : XML error: Attempted double use of PCI Address 0000:00:03.0
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish create domain, duration 0.01 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 instance(43015e80-1d17-4683-965f Finish instance creation, duration 0.84 seconds
Jun 29 11:29:48 andy-200628-amai3ieg-sf-3 Returning API error: 500, server error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 104, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 614, in post
        instance.create(lock=lock)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 220, in create
        self.power_on()
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 427, in power_on
        instance = conn.defineXML(xml)
      File "/usr/lib/python3/dist-packages/libvirt.py", line 3621, in defineXML
        if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
    libvirt.libvirtError: XML error: Attempted double use of PCI Address 0000:00:03.0
Jun 29 11:29:48 andy-200628-amai3ieg-sf-1 Returning proxied request: 500, {"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 104, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 108, in wrapper\n    return fn(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 614, in post\n    instance.create(lock=lock)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py\", line 220, in create\n    self.power_on()\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py\", line 427, in power_on\n    instance = conn.defineXML(xml)\n  File \"/usr/lib/python3/dist-packages/libvirt.py\", line 3621, in defineXML\n    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)\nlibvirt.libvirtError: XML error: Attempted double use of PCI Address 0000:00:03.0\n"}
Jun 29 11:29:48 localhost gunicorn.sf.access: [9229] 127.0.0.1 - - [29/Jun/2020:11:29:48 +0000] "POST /instances HTTP/1.1" 500 991 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.1.2"
```

**Comment by mikalstill** [comment]
This can be corrected solely with a template change, so I have moved the bug to the deployment project.

**Comment by mikalstill** [comment]
Ok, so this now works, although cirros does not appear to DHCP on all interfaces...

```
root@sf-1:/srv/shakenfist/deploy# sf-client network create 192.168.1.0/24 net1
uuid        : 86e09fbb-8617-4dbc-9b82-419cc857ebe5
name        : net1
vxlan id    : 3
netblock    : 192.168.1.0/24
provide dhcp: True
provide nat : True
namespace   : system
root@sf-1:/srv/shakenfist/deploy# sf-client network create 192.168.2.0/24 net2
uuid        : 554873e0-2064-4d1b-a1f4-3ba300c246e8
name        : net2
vxlan id    : 4
netblock    : 192.168.2.0/24
provide dhcp: True
provide nat : True
namespace   : system
root@sf-1:/srv/shakenfist/deploy# sf-client instance create foo 1 1 -d 8@cirros -n 86e09fbb-8617-4dbc-9b82-419cc857ebe5 -n 554873e0-2064-4d1b-a1f4-3ba300c246e8
uuid        : 4b08d975-589e-454e-9548-dfd750334c36
name        : foo
namespace   : system
cpus        : 1
memory      : 1024
disk spec   : [{'base': 'cirros', 'bus': None, 'size': 8, 'type': 'disk'}]
node        : sf-3
state       : created
console port: 31256
vdi port    : 32391

ssh key     : None
user data   : None

Interfaces:

    uuid    : aba71592-b6b8-40e6-a31f-6cb378cbcc33
    network : 86e09fbb-8617-4dbc-9b82-419cc857ebe5
    macaddr : 00:00:00:9c:b0:83
    order   : 0
    ipv4    : 192.168.1.138
    floating: None

    uuid    : b1ec6d53-ed38-4857-a6f4-c4e436bf1266
    network : 554873e0-2064-4d1b-a1f4-3ba300c246e8
    macaddr : 00:00:00:6b:19:15
    order   : 1
    ipv4    : 192.168.2.254
    floating: None
root@sf-1:/srv/shakenfist/deploy# telnet sf-3 31256
Trying 10.1.1.104...
Connected to sf-3.
Escape character is '^]'.

login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
foo login: cirros
Password: 
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:00:00:9C:B0:83  
          inet addr:192.168.1.138  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::200:ff:fe9c:b083/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:46 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4785 (4.6 KiB)  TX bytes:2377 (2.3 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

$ dmesg | grep eth
[    3.724171] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
$ ifconfig eth1 inet 192.168.2.42 up
ifconfig: SIOCSIFADDR: Operation not permitted
$ sudo ifconfig eth1 inet 192.168.2.42 up
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:00:00:9C:B0:83  
          inet addr:192.168.1.138  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::200:ff:fe9c:b083/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:50 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5065 (4.9 KiB)  TX bytes:2377 (2.3 KiB)

eth1      Link encap:Ethernet  HWaddr 00:00:00:6B:19:15  
          inet addr:192.168.2.42  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::200:ff:fe6b:1915/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2112 (2.0 KiB)  TX bytes:426 (426.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

$ ping 192.168.2.1
PING 192.168.2.1 (192.168.2.1): 56 data bytes
64 bytes from 192.168.2.1: seq=0 ttl=64 time=0.905 ms
64 bytes from 192.168.2.1: seq=1 ttl=64 time=0.559 ms
^C
--- 192.168.2.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.559/0.732/0.905 ms
$ ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=0.594 ms
64 bytes from 192.168.1.1: seq=1 ttl=64 time=0.569 ms
^C
--- 192.168.1.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.569/0.581/0.594 ms
$ 
```

**Comment by mikalstill** [comment]
And I can fix that with user data of course. I should have an implemented CI test to cover this soon.
